#ifndef LIBRARY_IMPLEMENTATIONS_CPP
#define LIBRARY_IMPLEMENTATIONS_CPP

#define STB_IMAGE_IMPLEMENTATION
#include "libraries/stb_image.h"
#undef STB_IMAGE_IMPLEMENTATION
#define STB_TRUETYPE_IMPLEMENTATION
#include "libraries\stb_truetype.h"
#undef STB_TRUETYPE_IMPLEMENTATION

#endif //LIBRARY_IMPLEMENTATIONS_CPP